# Generated by Django 4.2.3 on 2023-08-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RenameField('Model', 'app_lesson_4_advetisement', 'advertisement'),
        migrations.CreateModel(
            name='Advetisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='название')),
                ('desc', models.TextField(verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('torg', models.BooleanField(help_text='возможен ли торг', verbose_name='торг')),
                ('ca', models.DateField(auto_now_add=True)),
                ('ua', models.DateField(auto_now=True)),
            ],
        ),
    ]
